version: '3.8'

services:
  crm-frontend:
    image: node:16
    container_name: crm-frontend
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "4200:4200"
    command: "npm start"
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge
